<Project>
    <PropertyGroup>
        <AssemblyDir>$(MSBuildThisFileDirectory)Assets\Assemblies</AssemblyDir>
        <AssemblyCSharpDir>$(MSBuildThisFileDirectory)Assets\Assemblies\AssemblyCSharp</AssemblyCSharpDir>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="0Harmony" HintPath="$(AssemblyDir)\0Harmony.dll" Private="False" />
        <Reference Include="Accessibility" HintPath="$(AssemblyCSharpDir)\Accessibility.dll" Private="False" />
        <Reference Include="AmplifyMotion" HintPath="$(AssemblyCSharpDir)\AmplifyMotion.dll" Private="False" />
        <Reference Include="AnimationSystem.Recording" HintPath="$(AssemblyCSharpDir)\AnimationSystem.Recording.dll" Private="False" />
        <Reference Include="AnimationSystem.Types" HintPath="$(AssemblyCSharpDir)\AnimationSystem.Types.dll" Private="False" />
        <Reference Include="Assembly-CSharp-firstpass" HintPath="$(AssemblyCSharpDir)\Assembly-CSharp-firstpass.dll" Private="False" />
        <Reference Include="Assembly-CSharp" HintPath="$(AssemblyCSharpDir)\Assembly-CSharp.dll" Private="False" />
        <Reference Include="Autodesk.Fbx" HintPath="$(AssemblyCSharpDir)\Autodesk.Fbx.dll" Private="False" />
        <Reference Include="bsg.componentace.compression.libs.zlib" HintPath="$(AssemblyCSharpDir)\bsg.componentace.compression.libs.zlib.dll" Private="False" />
        <Reference Include="bsg.console.core" HintPath="$(AssemblyCSharpDir)\bsg.console.core.dll" Private="False" />
        <Reference Include="bsg.microsoft.extensions.objectpool" HintPath="$(AssemblyCSharpDir)\bsg.microsoft.extensions.objectpool.dll" Private="False" />
        <Reference Include="bsg.system.buffers" HintPath="$(AssemblyCSharpDir)\bsg.system.buffers.dll" Private="False" />
        <Reference Include="BSG.Unity.Wires" HintPath="$(AssemblyCSharpDir)\BSG.Unity.Wires.dll" Private="False" />
        <Reference Include="Cinemachine" HintPath="$(AssemblyCSharpDir)\Cinemachine.dll" Private="False" />
        <Reference Include="Coffee.SoftMaskForUGUI" HintPath="$(AssemblyCSharpDir)\Coffee.SoftMaskForUGUI.dll" Private="False" />
        <Reference Include="com.nvidia.reflex.Runtime" HintPath="$(AssemblyCSharpDir)\com.nvidia.reflex.Runtime.dll" Private="False" />
        <Reference Include="Comfort" HintPath="$(AssemblyCSharpDir)\Comfort.dll" Private="False" />
        <Reference Include="Comfort.Unity" HintPath="$(AssemblyCSharpDir)\Comfort.Unity.dll" Private="False" />
        <Reference Include="CommonExtensions" HintPath="$(AssemblyCSharpDir)\CommonExtensions.dll" Private="False" />
        <Reference Include="DissonanceVoip" HintPath="$(AssemblyCSharpDir)\DissonanceVoip.dll" Private="False" />
        <Reference Include="DOTween" HintPath="$(AssemblyCSharpDir)\DOTween.dll" Private="False" />
        <Reference Include="DOTween.Modules" HintPath="$(AssemblyCSharpDir)\DOTween.Modules.dll" Private="False" />
        <Reference Include="ItemComponent.Types" HintPath="$(AssemblyCSharpDir)\ItemComponent.Types.dll" Private="False" />
        <Reference Include="ItemTemplate.Types" HintPath="$(AssemblyCSharpDir)\ItemTemplate.Types.dll" Private="False" />
        <Reference Include="JBooth.MicroSplat.Core" HintPath="$(AssemblyCSharpDir)\JBooth.MicroSplat.Core.dll" Private="False" />
        <Reference Include="kcp" HintPath="$(AssemblyCSharpDir)\kcp.dll" Private="False" />
        <Reference Include="LibraryLoaderUtility" HintPath="$(AssemblyCSharpDir)\LibraryLoaderUtility.dll" Private="False" />
        <Reference Include="Meta.XR.Audio" HintPath="$(AssemblyCSharpDir)\Meta.XR.Audio.dll" Private="False" />
        <Reference Include="Mono.Data.Sqlite" HintPath="$(AssemblyCSharpDir)\Mono.Data.Sqlite.dll" Private="False" />
        <Reference Include="Mono.Posix" HintPath="$(AssemblyCSharpDir)\Mono.Posix.dll" Private="False" />
        <Reference Include="Mono.Security" HintPath="$(AssemblyCSharpDir)\Mono.Security.dll" Private="False" />
        <Reference Include="Mono.WebBrowser" HintPath="$(AssemblyCSharpDir)\Mono.WebBrowser.dll" Private="False" />
        <Reference Include="Newtonsoft.Json" HintPath="$(AssemblyCSharpDir)\Newtonsoft.Json.dll" Private="False" />
        <Reference Include="Newtonsoft.Json.UnityConverters" HintPath="$(AssemblyCSharpDir)\Newtonsoft.Json.UnityConverters.dll" Private="False" />
        <Reference Include="NLog" HintPath="$(AssemblyCSharpDir)\NLog.dll" Private="False" />
        <Reference Include="Novell.Directory.Ldap" HintPath="$(AssemblyCSharpDir)\Novell.Directory.Ldap.dll" Private="False" />
        <Reference Include="Sirenix.OdinInspector.Attributes" HintPath="$(AssemblyCSharpDir)\Sirenix.OdinInspector.Attributes.dll" Private="False" />
        <Reference Include="Sirenix.Serialization.Config" HintPath="$(AssemblyCSharpDir)\Sirenix.Serialization.Config.dll" Private="False" />
        <Reference Include="Sirenix.Serialization" HintPath="$(AssemblyCSharpDir)\Sirenix.Serialization.dll" Private="False" />
        <Reference Include="Sirenix.Utilities" HintPath="$(AssemblyCSharpDir)\Sirenix.Utilities.dll" Private="False" />
        <Reference Include="uLipSync.Runtime" HintPath="$(AssemblyCSharpDir)\uLipSync.Runtime.dll" Private="False" />
        <Reference Include="Unity.AI.Navigation" HintPath="$(AssemblyCSharpDir)\Unity.AI.Navigation.dll" Private="False" />
        <Reference Include="Unity.Burst" HintPath="$(AssemblyCSharpDir)\Unity.Burst.dll" Private="False" />
        <Reference Include="Unity.Burst.Unsafe" HintPath="$(AssemblyCSharpDir)\Unity.Burst.Unsafe.dll" Private="False" />
        <Reference Include="Unity.Collections" HintPath="$(AssemblyCSharpDir)\Unity.Collections.dll" Private="False" />
        <Reference Include="Unity.Collections.LowLevel.ILSupport" HintPath="$(AssemblyCSharpDir)\Unity.Collections.LowLevel.ILSupport.dll" Private="False" />
        <Reference Include="Unity.Formats.Fbx.Runtime" HintPath="$(AssemblyCSharpDir)\Unity.Formats.Fbx.Runtime.dll" Private="False" />
        <Reference Include="Unity.Mathematics" HintPath="$(AssemblyCSharpDir)\Unity.Mathematics.dll" Private="False" />
        <Reference Include="Unity.MemoryProfiler" HintPath="$(AssemblyCSharpDir)\Unity.MemoryProfiler.dll" Private="False" />
        <Reference Include="Unity.PlayableGraphVisualizer" HintPath="$(AssemblyCSharpDir)\Unity.PlayableGraphVisualizer.dll" Private="False" />
        <Reference Include="Unity.Postprocessing.Runtime" HintPath="$(AssemblyCSharpDir)\Unity.Postprocessing.Runtime.dll" Private="False" />
        <Reference Include="Unity.ProBuilder.Csg" HintPath="$(AssemblyCSharpDir)\Unity.ProBuilder.Csg.dll" Private="False" />
        <Reference Include="Unity.ProBuilder" HintPath="$(AssemblyCSharpDir)\Unity.ProBuilder.dll" Private="False" />
        <Reference Include="Unity.ProBuilder.KdTree" HintPath="$(AssemblyCSharpDir)\Unity.ProBuilder.KdTree.dll" Private="False" />
        <Reference Include="Unity.ProBuilder.Poly2Tri" HintPath="$(AssemblyCSharpDir)\Unity.ProBuilder.Poly2Tri.dll" Private="False" />
        <Reference Include="Unity.ProBuilder.Stl" HintPath="$(AssemblyCSharpDir)\Unity.ProBuilder.Stl.dll" Private="False" />
        <Reference Include="Unity.Profiling.Core" HintPath="$(AssemblyCSharpDir)\Unity.Profiling.Core.dll" Private="False" />
        <Reference Include="Unity.Recorder.Base" HintPath="$(AssemblyCSharpDir)\Unity.Recorder.Base.dll" Private="False" />
        <Reference Include="Unity.Recorder" HintPath="$(AssemblyCSharpDir)\Unity.Recorder.dll" Private="False" />
        <Reference Include="Unity.ScriptableBuildPipeline" HintPath="$(AssemblyCSharpDir)\Unity.ScriptableBuildPipeline.dll" Private="False" />
        <Reference Include="Unity.TextMeshPro" HintPath="$(AssemblyCSharpDir)\Unity.TextMeshPro.dll" Private="False" />
        <Reference Include="Unity.Timeline" HintPath="$(AssemblyCSharpDir)\Unity.Timeline.dll" Private="False" />
        <Reference Include="UnityEngine.AccessibilityModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AccessibilityModule.dll" Private="False" />
        <Reference Include="UnityEngine.AIModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AIModule.dll" Private="False" />
        <Reference Include="UnityEngine.AndroidJNIModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AndroidJNIModule.dll" Private="False" />
        <Reference Include="UnityEngine.AnimationModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AnimationModule.dll" Private="False" />
        <Reference Include="UnityEngine.ARModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ARModule.dll" Private="False" />
        <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AssetBundleModule.dll" Private="False" />
        <Reference Include="UnityEngine.AudioModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.AudioModule.dll" Private="False" />
        <Reference Include="UnityEngine.ClothModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ClothModule.dll" Private="False" />
        <Reference Include="UnityEngine.ClusterInputModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ClusterInputModule.dll" Private="False" />
        <Reference Include="UnityEngine.ClusterRendererModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ClusterRendererModule.dll" Private="False" />
        <Reference Include="UnityEngine.ContentLoadModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ContentLoadModule.dll" Private="False" />
        <Reference Include="UnityEngine.CoreModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.CoreModule.dll" Private="False" />
        <Reference Include="UnityEngine.CrashReportingModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.CrashReportingModule.dll" Private="False" />
        <Reference Include="UnityEngine.DirectorModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.DirectorModule.dll" Private="False" />
        <Reference Include="UnityEngine" HintPath="$(AssemblyCSharpDir)\UnityEngine.dll" Private="False" />
        <Reference Include="UnityEngine.DSPGraphModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.DSPGraphModule.dll" Private="False" />
        <Reference Include="UnityEngine.GameCenterModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.GameCenterModule.dll" Private="False" />
        <Reference Include="UnityEngine.GIModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.GIModule.dll" Private="False" />
        <Reference Include="UnityEngine.GridModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.GridModule.dll" Private="False" />
        <Reference Include="UnityEngine.HotReloadModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.HotReloadModule.dll" Private="False" />
        <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ImageConversionModule.dll" Private="False" />
        <Reference Include="UnityEngine.IMGUIModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.IMGUIModule.dll" Private="False" />
        <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.InputLegacyModule.dll" Private="False" />
        <Reference Include="UnityEngine.InputModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.InputModule.dll" Private="False" />
        <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.JSONSerializeModule.dll" Private="False" />
        <Reference Include="UnityEngine.LocalizationModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.LocalizationModule.dll" Private="False" />
        <Reference Include="UnityEngine.NVIDIAModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.NVIDIAModule.dll" Private="False" />
        <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ParticleSystemModule.dll" Private="False" />
        <Reference Include="UnityEngine.PerformanceReportingModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.PerformanceReportingModule.dll" Private="False" />
        <Reference Include="UnityEngine.Physics2DModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.Physics2DModule.dll" Private="False" />
        <Reference Include="UnityEngine.PhysicsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.PhysicsModule.dll" Private="False" />
        <Reference Include="UnityEngine.ProfilerModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ProfilerModule.dll" Private="False" />
        <Reference Include="UnityEngine.PropertiesModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.PropertiesModule.dll" Private="False" />
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll" Private="False" />
        <Reference Include="UnityEngine.ScreenCaptureModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.ScreenCaptureModule.dll" Private="False" />
        <Reference Include="UnityEngine.SharedInternalsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.SharedInternalsModule.dll" Private="False" />
        <Reference Include="UnityEngine.SpriteMaskModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.SpriteMaskModule.dll" Private="False" />
        <Reference Include="UnityEngine.SpriteShapeModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.SpriteShapeModule.dll" Private="False" />
        <Reference Include="UnityEngine.StreamingModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.StreamingModule.dll" Private="False" />
        <Reference Include="UnityEngine.SubstanceModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.SubstanceModule.dll" Private="False" />
        <Reference Include="UnityEngine.SubsystemsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.SubsystemsModule.dll" Private="False" />
        <Reference Include="UnityEngine.TerrainModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TerrainModule.dll" Private="False" />
        <Reference Include="UnityEngine.TerrainPhysicsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TerrainPhysicsModule.dll" Private="False" />
        <Reference Include="UnityEngine.TextCoreFontEngineModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TextCoreFontEngineModule.dll" Private="False" />
        <Reference Include="UnityEngine.TextCoreTextEngineModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TextCoreTextEngineModule.dll" Private="False" />
        <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TextRenderingModule.dll" Private="False" />
        <Reference Include="UnityEngine.TilemapModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TilemapModule.dll" Private="False" />
        <Reference Include="UnityEngine.TLSModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.TLSModule.dll" Private="False" />
        <Reference Include="UnityEngine.UI" HintPath="$(AssemblyCSharpDir)\UnityEngine.UI.dll" Private="False" />
        <Reference Include="UnityEngine.UIElementsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UIElementsModule.dll" Private="False" />
        <Reference Include="UnityEngine.UIModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UIModule.dll" Private="False" />
        <Reference Include="UnityEngine.UmbraModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UmbraModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityAnalyticsCommonModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityAnalyticsModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityAnalyticsModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityConnectModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityConnectModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityCurlModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityCurlModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityTestProtocolModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityTestProtocolModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityWebRequestAssetBundleModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityWebRequestAudioModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityWebRequestAudioModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityWebRequestModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityWebRequestTextureModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityWebRequestTextureModule.dll" Private="False" />
        <Reference Include="UnityEngine.UnityWebRequestWWWModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.UnityWebRequestWWWModule.dll" Private="False" />
        <Reference Include="UnityEngine.VehiclesModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.VehiclesModule.dll" Private="False" />
        <Reference Include="UnityEngine.VFXModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.VFXModule.dll" Private="False" />
        <Reference Include="UnityEngine.VideoModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.VideoModule.dll" Private="False" />
        <Reference Include="UnityEngine.VirtualTexturingModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.VirtualTexturingModule.dll" Private="False" />
        <Reference Include="UnityEngine.VRModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.VRModule.dll" Private="False" />
        <Reference Include="UnityEngine.WindModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.WindModule.dll" Private="False" />
        <Reference Include="UnityEngine.XRModule" HintPath="$(AssemblyCSharpDir)\UnityEngine.XRModule.dll" Private="False" />
        <Reference Include="websocket-sharp" HintPath="$(AssemblyCSharpDir)\websocket-sharp.dll" Private="False" />
        <Reference Include="where-allocations" HintPath="$(AssemblyCSharpDir)\where-allocations.dll" Private="False" />
    </ItemGroup>
</Project>