using AssemblyLib;
using CliFx;
using CliFx.Attributes;
using CliFx.Infrastructure;

namespace AssemblyTool.Commands;

[Command("patch", Description = "Runs only the patching process on an unpatched dll generated by this tool")]
public class Patch : ICommand
{
    [CommandParameter(
        0,
        IsRequired = true,
        Description = "The absolute path to the unpatched target dll, folder must contain all references to be resolved"
    )]
    public required string TargetAssemblyPath { get; init; }

    public ValueTask ExecuteAsync(IConsole console)
    {
        var app = new App();
        app.RunPatch(TargetAssemblyPath);

        return ValueTask.CompletedTask;
    }
}
