<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>EftCodeStub</RootNamespace>
  </PropertyGroup>
  <Import Project="..\AssemblyImport.props" />
</Project>
